# Generated by Django 5.1.2 on 2025-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('water_used', models.FloatField(default=0.0)),
                ('people_using', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CapacityBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainings_count', models.PositiveIntegerField(default=0)),
                ('modules', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FodderFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=20, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('land_acreage_leased', models.FloatField(default=0.0)),
                ('land_acreage_sharing_model', models.TextField(blank=True)),
                ('yield_per_harvest', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='HayStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bales_stored', models.PositiveIntegerField(default=0)),
                ('bales_given_or_sold', models.PositiveIntegerField(default=0)),
                ('revenue_made', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=20, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('male_goats', models.PositiveIntegerField(default=0)),
                ('female_goats', models.PositiveIntegerField(default=0)),
                ('age', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('weekly_offtake', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('vaccination_schedule', models.TextField(blank=True)),
                ('goats_given', models.PositiveIntegerField(default=0)),
                ('tracking_traceability', models.TextField(blank=True)),
            ],
        ),
    ]
