# Generated by Django 5.1.2 on 2025-01-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugnumber', models.IntegerField(default=0)),
                ('newbreeding', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='female_goats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='goats_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='male_goats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='weekly_offtake',
            field=models.IntegerField(default=0),
        ),
    ]
