# Generated by Django 5.1.2 on 2025-01-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasystem', '0002_breeding_alter_livestockfarmer_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='breeding',
        ),
        migrations.AddField(
            model_name='fodderfarmer',
            name='newbreeding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fodderfarmer',
            name='tugnumber',
            field=models.IntegerField(default=0),
        ),
    ]
