# Generated by Django 5.1.2 on 2025-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasystem', '0003_delete_breeding_fodderfarmer_newbreeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockfarmer',
            name='age',
            field=models.IntegerField(choices=[('1-6', '1-6 months'), ('7-12', '7-12 months'), ('13-18', '13-18 months'), ('19-25', '19-25 months'), ('2.5+', '2.5 years and above')], default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='weight',
            field=models.FloatField(choices=[('1-7', '1-7 kgs'), ('8-15', '8-15 kgs'), ('16-23', '16-23 kgs'), ('24-31', '24-31 kgs'), ('32-39', '32-39 kgs'), ('40-47', '40-47 kgs'), ('48-55', '48-55 kgs')], default=0.0),
        ),
    ]
