# Generated by Django 5.1.2 on 2025-01-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasystem', '0004_alter_livestockfarmer_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockfarmer',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livestockfarmer',
            name='count2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='age',
            field=models.IntegerField(choices=[('1-6', '1-6 months'), ('7-12', '7-12 months'), ('13-18', '13-18 months'), ('19-25', '19-25 months'), ('2.5+', '25 months and above')], default=0),
        ),
    ]
