# Generated by Django 5.1.2 on 2025-01-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasystem', '0005_livestockfarmer_count_livestockfarmer_count2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestockfarmer',
            old_name='count2',
            new_name='age_number',
        ),
        migrations.RenameField(
            model_name='livestockfarmer',
            old_name='age',
            new_name='age_range',
        ),
        migrations.RenameField(
            model_name='livestockfarmer',
            old_name='count',
            new_name='weight_number',
        ),
        migrations.RenameField(
            model_name='livestockfarmer',
            old_name='weight',
            new_name='weight_range',
        ),
    ]
