# Generated by Django 5.1.2 on 2025-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasystem', '0007_remove_livestockfarmer_vaccination_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borehole',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fodderfarmer',
            name='id_no',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fodderfarmer',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fodderfarmer',
            name='newbreeding',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fodderfarmer',
            name='phone_no',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='fodderfarmer',
            name='tugnumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='age_range',
            field=models.CharField(blank=True, choices=[('1-6', '1-6 months'), ('7-12', '7-12 months'), ('13-18', '13-18 months'), ('19-25', '19-25 months'), ('2.5+', '25 months and above')], max_length=10),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='date_administered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='female_goats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='goats_given',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='id_no',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='male_goats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='phone_no',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='vaccin_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='weekly_offtake',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livestockfarmer',
            name='weight_range',
            field=models.CharField(blank=True, choices=[('1-7', '1-7 kgs'), ('8-15', '8-15 kgs'), ('16-23', '16-23 kgs'), ('24-31', '24-31 kgs'), ('32-39', '32-39 kgs'), ('40-47', '40-47 kgs'), ('48-55', '48-55 kgs')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='livestockfarmer',
            constraint=models.CheckConstraint(condition=models.Q(('male_goats__gte', 0)), name='male_goats_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='livestockfarmer',
            constraint=models.CheckConstraint(condition=models.Q(('female_goats__gte', 0)), name='female_goats_non_negative'),
        ),
    ]
